name: toolchain-build
description: 'Builds the selected toolchain'
inputs:
  tools-version:
    description: Which toolchain to build
    required: false
    default: 'riscv-tools'
runs:
  using: "composite"
  steps:
    - run: echo TOOLCHAIN-BUILD ${{ inputs.tools-version }} > ${{ inputs.tools-version }}-toolchain-artifact
      shell: bash
    - uses: actions/cache@v2
      id: toolchain-id
      with:
        path: ${{ inputs.tools-version }}
        key: ${{ inputs.tools-version }}
        restore-keys: ${{ inputs.tools-version }}
    - name: run stuff
      run: |
        echo "abcdef" > ${{ inputs.tools-version }}
      shell: bash


