name: 'GoodBye'
description: 'Greet someone'
inputs:
  who-to-bye:  # id of input
    description: 'Who to greet'
    required: true
    default: 'Planet'
runs:
  using: "composite"
  steps:
    - run: echo I dont know why you say goodbye ${{ inputs.who-to-bye }}.
      shell: bash
    - run: echo github-actions-path ${{ github.action_path }}
      shell: bash
#    - id: random-number-generator
#      run: echo "::set-output name=random-id::$(echo $RANDOM)"
#      shell: bash
#    - run: ${{ github.action_path }}/goodbye.sh
#      shell: bash