name: fixed-key
description: 'Runs cache with fixed key'

runs:
  using: "composite"
  steps:
    - run: echo TOOLCHAIN-BUILD FIXED-KEY
      shell: bash
    - uses: actions/cache@v2
      id: toolchain-id
      with:
        path: MY-CACHE-KEY
        key: MY-CACHE-KEY
        restore-keys: MY-CACHE-KEY
    - name: run stuff
      run: echo "fixed-key-data" > MY-CACHE-KEY
      shell: bash


