name: fixed-key
description: 'Runs cache with fixed key'

inputs:
  unused:
    description: "dog"
    required: false
    default: fox
runs:
  using: "composite"
  steps:
    - run: echo TOOLCHAIN-BUILD FIXED-KEY
      shell: bash
    - uses: actions/cache@v2
      id: toolchain-id
      with:
        path: MY-CACHE-KEY
        key: MY-CACHE-KEY
        restore-keys: MY-CACHE-KEY
    - name: run stuff
      run: |
        if [[ ${{ steps.toolchain-id.outputs.cache-hit }} != 'true' ]]; then
          echo "fixed-key-data" > MY-CACHE-KEY
        else
          echo "cache hit do not run"
        fi
      shell: bash
    - name: done
      run: echo done
      shell: bash


