on: [push]

jobs:
  install-riscv-toolchain:
    runs-on: ubuntu-latest
    name: build-and-test-chipyard-integration
    steps:
      - uses: actions/checkout@v2
      - id: install-riscv-toolchain
        uses: ./.github/actions/install-riscv-toolchain
      - name: show artifact
        run: cat riscv-toolchain-artifact