on: [push]

jobs:
  install-riscv-toolchain:
    runs-on: ubuntu-latest
    name: build-and-test-chipyard-integration
    steps:
      - id: install-riscv-toolchain
        uses: ./.github/actions/install-riscv-toolchain
      - id: install-esp-toolchain
        uses: ./.github/actions/install-riscv-toolchain
      - name: show artifact
        run: cat riscv-toolchain-artifact
      - name: Show directory
        run: ls -ltr