on: [push]

jobs:
  install-riscv-toolchain:
    runs-on: ubuntu-latest
    name: build-and-test-chipyard-integration
    steps:
      - uses: actions/checkout@v2
      - id: install-riscv-toolchain
        uses: ./.github/actions/install-riscv-toolchain
      - id: install-esp-toolchain
        uses: ./.github/actions/install-esp-toolchain
      - id: build-verilator
        uses: ./.github/actions/install-verilator
        with:
          build-server: ${{ secrets.BUILDSERVER }}
          build-user: ${{ secrets.BUILDUSER }}
      - id: run-fixed-key
        uses: ./.github/actions/fixed-key
      - name: show artifact
        run: |
          cat riscv-tools-toolchain-artifact
          cat esp-tools-toolchain-artifact
          cat build-verilator
          cat MY-CACHE-KEY
      - name: Show directory
        run: ls -ltr